# Generated by Django 3.2.8 on 2021-10-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Birthday Date', models.DateField(verbose_name='Birthday Date')),
                ('birthday_person_name', models.CharField(max_length=255, verbose_name='Birthday Person Name')),
                ('birthday_person_email', models.CharField(max_length=255, verbose_name='Birthday Person Email')),
                ('birthday_message', models.TextField(verbose_name='Birthday Message')),
                ('sender_email', models.CharField(max_length=255, verbose_name='Email Sender')),
            ],
            options={
                'verbose_name': 'Birthday Reminder',
                'verbose_name_plural': 'Birthday Reminders',
            },
        ),
    ]
