# Generated by Django 3.2.8 on 2021-10-10 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birthdayreminder',
            old_name='Birthday Date',
            new_name='birthday_date',
        ),
    ]
